blog/urls.py
from django.conf.urls import url
from . import views, feed

urlpatterns = [
    url(r'^$', views.BlogIndex.as_view(), name="blog"),
    url(r'^tag/(?P<slug>\S+)$', views.TagIndex.as_view(), name="tag_index"),
    url(r'^feed/$', feed.LatestPosts(), name="feed"),
    url(r'^(?P<slug>\S+)$', views.BlogDetail.as_view(),
        name="entry_detail"),
]

heidik/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^markdown/', include('django_markdown.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^', include('mainpage.urls')),
]

mainpage/urls.py
from django.conf.urls import url, patterns, include
from django.views.generic.base import TemplateView
from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name="index"),
    url(r'^about/$', views.AboutView.as_view(), name="about"),
    url(r'^game/tictactoe$', views.GameView.as_view(), name="game"),
    ]

blog/models.py
from django.db import models
from django.core.urlresolvers import reverse

class EntryQuerySet(models.QuerySet):
    def published(self):
        return self.filter(publish = True)
    
class Tag(models.Model):
    slug = models.SlugField(max_length=200, unique=True)

    def __str__(self):
        return self.slug
    
    def get_absolute_url(self):
        return reverse("tag_index", kwargs={"slug": self.slug})

class Entry(models.Model):
    title = models.CharField(max_length = 200)
    body = models.TextField()
    slug = models.SlugField(max_length = 200, unique = True)
    publish = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add = True)
    modified = models.DateTimeField(auto_now = True)
    
    tags = models.ManyToManyField(Tag)
    
    objects = EntryQuerySet.as_manager()
    
    def get_absolute_url(self):
        return reverse("entry_detail", kwargs={"slug": self.slug})

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name = "Blog Entry"
        verbose_name_plural = "Blog Entries"
        ordering = ["-created"]

mainpage/models.py
from django.db import models


class MainContent(models.Model):
    header = models.CharField(max_length = 200)
    content = models.TextField()
    page = models.CharField(max_length = 20, default="index")
    
    def __str__(self):
        return self.header
    
    
    

blog/views.py
from django.shortcuts import render
from django.views import generic
from . import models
from django.http import HttpResponse


class BlogIndex(generic.ListView):
    queryset = models.Entry.objects.published()
    template_name = "blog/blog.html"
    paginate_by = 3

class BlogDetail(generic.DetailView):
    model = models.Entry
    template_name = "blog/post.html"

class TagIndex(generic.ListView):
    template_name = 'blog/blog.html'
    paginate_by = 3
    
    def get_queryset(self):
        slug = self.kwargs['slug']
        tag = models.Tag.objects.get(slug=slug)
        results = models.Entry.objects.filter(tags=tag)
        return results

mainpage/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.views.generic.base import TemplateView
from . import models


class IndexView(generic.ListView):
    template_name = 'mainpage/index.html'
    context_object_name = 'content_object_list'
    
    def get_queryset(self):
        return models.MainContent.objects.filter(page="index")

class AboutView(generic.ListView):
    template_name = 'mainpage/index.html'
    context_object_name = 'content_object_list'
    
    def get_queryset(self):
        return models.MainContent.objects.filter(page="about")

class GameView(TemplateView):
    template_name = 'mainpage/tictactoe.html'

blog/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Heidi Kasemir blog">
    <meta name="author" content="Heidi Kasemir">
    <link rel="icon" href="{% static "icons/favicon.png" %}">
    <link href="/feed/" rel="alternate" type="application/rss+xml" title="HeidiK Blog Feed" />
    <title>Heidi Kasemir Blog</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "css/blog.css" %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="blog-masthead">
      <div class="container">
        <nav class="blog-nav">
          <a class="blog-nav-item active" href="{% url "index" %}">Home</a>
          <a class="blog-nav-item" href="#">About</a>
        </nav>
      </div>
    </div>

    <div class="container">

      <div class="blog-header">
        <h1 class="blog-title">HK Blog</h1>
        <p class="lead blog-description">My first blog written from scratch in Django</p>
      </div>

      <div class="row">

        <div class="col-sm-8 blog-main">
          {% block blog_entries %} {% endblock %}

          {% if is_paginated %}
            <ul class="pager">
              <li {% if not page_obj.has_previous %}class="disabled"{% endif %}><a {% if page_obj.has_previous %}href="?page={{ page_obj.previous_page_number }}"{% endif %}>Prev</a></li>
              <li {% if not page_obj.has_next %}class="disabled"{% endif %}><a {% if page_obj.has_next %}href="?page={{ page_obj.next_page_number }}"{% endif %}>Next</a></li>
            </ul>
    {% endif %}
        </div><!-- /.blog-main -->

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
          <div class="sidebar-module sidebar-module-inset">
            <h4>About</h4>
            <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
          </div>
        </div><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </div><!-- /.container -->

    <div class="blog-footer">
      <p>I want to put social media links here</p>
      <p><a href="#">Back to top</a>
      </p>
    </div>


    <!-- Bootstrap core JavaScript
    ================================================= -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/docs.min.js" %}"></script>
  </body>
</html>

templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Heidi Kasemir blog">
    <meta name="author" content="Heidi Kasemir">
    <link rel="icon" href="{% static "icons/favicon.png" %}">
    <link href="/feed/" rel="alternate" type="application/rss+xml" title="HeidiK Blog Feed" />
    <title>Heidi Kasemir Blog</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "blog/css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "blog/css/blog.css" %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="blog-masthead">
      <div class="container">
        <nav class="blog-nav">
          <a class="blog-nav-item active" href="{% url "index" %}">Home</a>
          <a class="blog-nav-item" href="{% url "about" %}">About</a>
        </nav>
      </div>
    </div>

    <div class="container">

      <div class="blog-header">
        <h1 class="blog-title">HK Blog</h1>
        <p class="lead blog-description">My first blog written from scratch in Django</p>
      </div>

      <div class="row">

        <div class="col-sm-8 blog-main">
          {% block blog_entries %} {% endblock %}

          {% if is_paginated %}
            <ul class="pager">
              <li {% if not page_obj.has_previous %}class="disabled"{% endif %}><a {% if page_obj.has_previous %}href="?page={{ page_obj.previous_page_number }}"{% endif %}>Prev</a></li>
              <li {% if not page_obj.has_next %}class="disabled"{% endif %}><a {% if page_obj.has_next %}href="?page={{ page_obj.next_page_number }}"{% endif %}>Next</a></li>
            </ul>
    {% endif %}
        </div><!-- /.blog-main -->

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
          <div class="sidebar-module sidebar-module-inset">
            <h4>About</h4>
            <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
          </div>
        </div><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </div><!-- /.container -->

    <div class="blog-footer">
      <p>I want to put social media links here</p>
      <p><a href="#">Back to top</a>
      </p>
    </div>

  </body>
</html>

templates/blog/blog.html
{% extends "main.html" %}
{% load django_markdown %}

{% block blog_entries %}
{% for object in object_list %}
  <div class="post">
    <h2><a href="{% url "blog:entry_detail" slug=object.slug %}">{{ object.title }}</a></h2>
    <p class="meta">
      {{ object.created|date:"M d, Y" }} tags: {% for tag in object.tags.all %} 
      <a class="post-category post-category-js" href="{% url "blog:tag_index" slug=tag.slug %}"> #{{ tag }} </a>{% endfor %}
    </p>
    <div class="post-body">
        {{ object.body|markdown }}
    </div>
  </div>
{% endfor %}
{% if is_paginated %}
    <ul class="pager">
      <li {% if not page_obj.has_previous %}class="disabled"{% endif %}><a {% if page_obj.has_previous %}href="?page={{ page_obj.previous_page_number }}"{% endif %}>Prev</a></li>
      <li {% if not page_obj.has_next %}class="disabled"{% endif %}><a {% if page_obj.has_next %}href="?page={{ page_obj.next_page_number }}"{% endif %}>Next</a></li>
    </ul>
{% endif %}
{% endblock %}

templates/blog/post.html
{% extends "main.html" %}
{% load django_markdown %}

{% block blog_entries %}
  <div class="post">
    <h2>{{ object.title }}</h2>
    <p class="meta">
      {{ object.created|date:"D M d, Y" }} |
      tags: {% for tag in object.tags.all %}<a class="post-category
      post-category-js" href="{% url 'blog:tag_index' slug=tag.slug %}"> #{{tag}}</a>
      {% endfor %}
    </p>
    <div class="post-body">
        {{ object.body|markdown }}
    </div>
  </div>
{% endblock %}

templates/mainpage/game/tictactoe.html
<!doctype html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title>Tic Tac Toe</title>
  <script src="tictactoe.js"></script>
  <link rel="stylesheet" href="tttstyle.css"></link>
</head>
<body>
 <div id='gamecontrols'>
 <p>Game Board Size:</p>
 <select name="size" id="boardsize">
   <option value="3">3</option>
   <option value="10">10</option>
   <option value="20">20</option>
 </select>
 <button id="refresh">Empty Board</button>
 </div>
 <div>
   <h2 id='gamestatus'>WINNER!</h2>
 </div>
  <div id="gameboard">
  </div>
</body>

</html>

templates/mainpage/index.html
{% extends "main.html" %}
{% load staticfiles %}



{% block mainContent %}
<a href="/static/mainpage/images/Optimized-DSC_4281.JPG">
  <img class="side-pic" src="{% static "mainpage/images/Optimized-DSC_4281.JPG" %}"></a>
{% for obj in content_object_list %}
  <div class="content">
    <h2>{{ obj.header }}</a></h2>
    <p>{{ obj.content }}</p>
  </div>
{% endfor %}
{% endblock %}

templates/mainpage/main.html
{% load staticfiles %}
<!DOCTYPE html>
<head>
  <title>Heidi Kasemir</title>
  <link rel="icon" href="{% static "icons/favicon.png" %}">
  <link href='http://fonts.googleapis.com/css?family=Josefin+Sans' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="{% static "mainpage/css/styles.css" %}">
  <meta name="viewport" content="width=device-width,initial-scale=1">
</head>
<body>
<header>
    <a href="{% url "index" %}">Heidi Kasemir</a>
    <div class="subtitle">Designer</div>
</header>
<nav>
    <ul>
        <li><a href="{% url "about" %}">About</a></li>
        <li><a href="{% url "blog:blog" %}">Blog</a></li>
        <li><a href="{% url "game" %}">Projects</a></li>
    </ul>
</nav>

<div class="container">

{% block mainContent %} {% endblock %}
{% block blog_entries %} {% endblock %}

</div>

<footer>
<ul class="social-icons">
    <li><a href="http://www.github.com/hkasemir" target="_blank"><span class="zocial-github"></span></a></li>
  <li><script>
    <!-- Begin
    user = "heidi.kasemir";
    site = "gmail.com";
    document.write('<a href=\"mailto:' + user + '@' + site + '\">');
    document.write('<span class="zocial-email"></span> ' + '</a>');
    // End -->
    </script></li>
    <li><a href="https://www.facebook.com/heidi.kasemir" target="_blank"><span class="zocial-facebook"></span></a></li>
    <li><a href="https://twitter.com/HeidiKasemir" target="_blank"><span class="zocial-twitter"></span></a></li>
    <li><a href="https://www.pinterest.com/heidikasemir/" target="_blank"><span class="zocial-pinterest"></span></a></li>
    <li><a href="https://www.linkedin.com/pub/heidi-kasemir/7b/627/a17" target="_blank"><span class="zocial-linkedin"></span></a></li>

    </ul>
</footer>
</body>

templates/mainpage/tictactoe.html
{% extends "main.html" %}
{% load staticfiles %}

{% block mainContent %}

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title>Tic Tac Toe</title>
  <script src="{% static "mainpage/js/tictactoe.js" %}"></script>
  <link rel="stylesheet" href="{% static "mainpage/css/tttstyle.css" %}">
</head>
<body>
 <div id='gamecontrols'>
 <p>Game Board Size:</p>
 <select name="size" id="boardsize">
   <option value="3">3</option>
   <option value="10">10</option>
   <option value="20">20</option>
 </select>
 <button id="refresh">Empty Board</button>
 </div>
 <div>
   <h2 id='gamestatus'>WINNER!</h2>
 </div>
  <div id="gameboard">
  </div>
</body>

{% endblock %}